# =====================================================================
# CONFIGURACIÓN MOSQUITTO BROKER PARA PRÁCTICA ROBÓTICA 2 (ESP32 MQTT)
# =====================================================================

# Permitir escucha en todas las interfaces de red de la PC (IPv4 e IPv6)
listener 1883 0.0.0.0

# Permitir conexiones anónimas sin usuario y contraseña (para facilidad de la práctica)
allow_anonymous true

# Habilitar persistencia de mensajes e historial de tópicos retenidos (LWT, etc.)
persistence true
persistence_location ./

# Logs y depuración en consola
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
