// Code generated by Arduino IoT Cloud, DO NOT EDIT.
// This file declares the 4 Cloud Variables for the Free Tier plan,
// registers the connection handler, and binds the cloud callbacks.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "INSERT_DEVICE_ID_HERE";

const char SSID[]               = SECRET_SSID;          // Network SSID (name) from arduino_secrets.h
const char PASS[]               = SECRET_OPTIONAL_PASS; // Network password from arduino_secrets.h
const char DEVICE_KEY[]         = SECRET_DEVICE_KEY;    // Secret device key from arduino_secrets.h

// Callback function prototypes for Cloud-to-Device commands
void onRoofVentChange();
void onSideVentChange();

// 4 Arduino IoT Cloud Variables (Free Tier limit - Basic UI Types)
float humidity;       // Floating Point Number: Sensor Telemetry (% Relative Humidity)
int   potentiometer;  // Integer Number: Sensor Telemetry (0 - 100%)
bool  roofVent;       // Boolean: Actuator 1 SG90 Roof Vent (true = OPEN / false = CLOSED)
bool  sideVent;       // Boolean: Actuator 2 SG90 Side Vent (true = OPEN / false = CLOSED)

void initProperties(){
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId("INSERT_THING_ID_HERE");

  // Read-only variables: update Cloud when local hardware changes
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(potentiometer, READ, ON_CHANGE, NULL);

  // Read & Write variables: bidirectional sync between Dashboard switch and Servos
  ArduinoCloud.addProperty(roofVent, READWRITE, ON_CHANGE, onRoofVentChange);
  ArduinoCloud.addProperty(sideVent, READWRITE, ON_CHANGE, onSideVentChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
